#!/usr/bin/env sh

echo "cURL and excute works."
for i in {1..100}
do
 echo `date` >> countfile
 echo $i >> countfile
done

curl https://raw.githubusercontent.com/alimgafar/random_stuff/master/curlfile > local_curlfile
