#!/usr/bin/env sh
clear
echo "cURL and excute works."
for i in {1..100}
do
 echo `date` >> countfile
 echo $i >> countfile
done

curl https://raw.githubusercontent.com/alimgafar/random_stuff/master/curlfile > local_curlfile
if [ -f random_stuff ]; then
 echo "It\'s already there."
else
 git clone https://github.com/alimgafar/random_stuff.git --progress
fi
